name: Azure Static Web Apps CI/CD (lemon-island)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: |
          npm run build
          cp public/staticwebapp.config.json dist/
      - name: Verify build output
        run: |
          echo "Build completed. Checking dist folder..."
          ls -la dist/
          echo "Assets folder contents:"
          ls -la dist/assets/
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LEMON_ISLAND_0CE3CF80F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./dist"
          skip_app_build: true
          skip_api_build: true
